config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create]
  get "/auth/twitter", as: :sign_in_with_twitter
  get "/auth/twitter/callback" => "callbacks#twitter"

  resources :nearby_campaigns, only: [:index]

  resources :campaigns do
    resources :pledges, only: [:new, :create]
    resources :publishings, only: [] do
      patch :update, on: :collection
    end
  end

  resources :pledges, only: [] do
    resources :payments, only: [:new, :create]
  end

  root 'campaigns#index'

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :campaigns
    end
  end

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :authenticate_user
  before_action :find_pledge

  def new
  end

  def create
    service = Pledges::HandlePayment.new({stripe_token: params[:stripe_token],
                                          user: current_user,
                                          pledge: @pledge
                                          })
    if service.call
      redirect_to @pledge.campaign, notice: "Thanks for completing the payment"
    else
      flash[:alert] = "Error handling payment, please try again"
      render :new
    end
  end

  private

  def find_pledge
    @pledge = Pledge.find params[:pledge_id]
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/new.html.erb
<h1>Make a payment</h1>

<div id="stripe-errors"></div>

<%= form_tag pledge_payments_path(@pledge), id: "submit-form" do %>
  <%= hidden_field_tag :stripe_token %>
<% end %>

<%= form_tag "", id: "payment-form" do %>
  <div class="form-group">
    <%= label_tag :card_number %>
    <%= text_field_tag :card_number, nil, data: {stripe: :number}, class: "form-control" %>
  </div>
  <div class="form-group">
  <%= label_tag "Expiration (MM/YY)" %>
  <%= select_month Date.today, {use_month_number: true}, {data: {stripe: :exp_month}, class: "form-control"} %>
  <%= select_year Date.today, {start_year: Date.today.year, end_year: Date.today.year + 10}, {data: {stripe: :exp_year}, class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= label_tag :cvc %>
    <%= text_field_tag :cvc, nil, data: {stripe: :cvc}, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= submit_tag "Make a Payment", class: "btn btn-primary" %>
  </div>
<% end %>