config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create]
  get "/auth/twitter", as: :sign_in_with_twitter
  get "/auth/twitter/callback" => "callbacks#twitter"

  resources :nearby_campaigns, only: [:index]

  resources :campaigns do
    resources :pledges, only: [:new, :create]
    resources :publishings, only: [] do
      patch :update, on: :collection
    end
  end

  resources :pledges, only: [] do
    resources :payments, only: [:new, :create]
  end

  root 'campaigns#index'

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :campaigns
    end
  end

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  belongs_to :user
  has_many :pledges, dependent: :destroy
  has_many :rewards, dependent: :destroy
  accepts_nested_attributes_for :rewards,
                                reject_if: :all_blank,
                                allow_destroy: true

  validates :title, presence: true, uniqueness: true
  validates :goal, presence: true, numericality:  {greater_than: 10}


  include AASM

  aasm whiny_transitions: false do
    state :draft, initial: true
    state :published
    state :canceled
    state :funded
    state :unfunded

    event :publish do
      transitions from: :draft, to: :published
    end

    event :fund do
      transitions from: :published, to: :funded
    end

    event :unfund do
      transitions from: :published, to: :unfunded
    end

    event :cancel do
      transitions from: [:draft, :published], to: :canceled
    end

  end





  geocoded_by :address   # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates

  def upcased_title
    title.upcase
  end

end

app/controllers/api/v1/campaigns_controller.rb
class Api::V1::CampaignsController < Api::BaseController




  def index
    @campaigns = Campaign.order(:created_at)
    # This will render /api/v1/views/index.json.jbuilde
  end

  def show
    campaign = Campaign.find params[:id]
    render json: campaign
  end

  def create
    campaign = Campaign.new campaign_params
    if campaign.save
      render json: campaign
    else
      render json: {errors: campaign.errors.full_messages}
    end
  end


  private

    def campaign_params
      params.require(:campaign).permit(:title, :body, :goal, :end_date)
    end


end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :find_campaign, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user, except: [:show, :index]

  def new
    @campaign = Campaign.new
    3.times { @campaign.rewards.build }
  end

  def show
  end

  def index
    @campaigns = Campaign.includes(:pledges).order(:created_at).references(:pledges)
    respond_to do |format|
      format.json { render json: @campaigns.to_json }
      format.html { render }
    end
  end

  def create
      @campaign = Campaign.new(campaign_params)
      @campaign.user = current_user
      if @campaign.save
        # CampaignGoalJob.set(wait_until: @campaign.end_date).perform_later(@campaign)
        redirect_to campaign_path(@campaign), notice: "Campaign created!"
      else
        gen_count = 3 - @campaign.rewards.size
        gen_count.times { @campaign.rewards.build }
        flash[:alert] = "Problem!"
        render :new
      end
    end

  def edit
  end

  def update
    if @campaign.update campaign_params
      redirect_to campaign_path(@campaign), notice: "Updated!"
    else
      render :edit
    end
  end

  def destroy
    @campaign.destroy
    redirect_to campaigns_path, notice: "Deleted!"
  end


private

  def find_campaign
    @campaign = Campaign.find(params[:id]).decorate
  end

  def campaign_params
    params.require(:campaign).permit(:title, :body, :goal, :end_date, :address,
                                    {rewards_attributes: [:amount, :description, :id, :_destroy]})
  end


end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaigns/_form.html.erb
<%= simple_form_for @campaign do |f| %>
  <%= f.input :title %>
  <%= f.input :body %>
  <%= f.input :goal, as: :string %>
  <%= f.input :end_date %>
  <%= f.input :address %>

  <h2> Rewards </h2>
  <div id="rewards">
    <%= f.simple_fields_for :rewards do |r| %>
      <%= render "reward_fields", f: r %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'add rewards', f, :rewards %>
    </div>
  </div>
  <%= f.submit class:"btn btn-primary"%>
<% end %>

app/views/campaigns/_reward_fields.html.erb
<div class="nested-fields">
  <h3>Reward</h3>
  <%= f.input :amount %>
  <%= f.input :description %>
  <%= link_to_remove_association "remove reward", f, class: "btn btn-danger btn-sm" %>
  <hr>
</div>

app/views/campaigns/edit.html.erb
<h1>Edit Campaign</h1>
<%= render "form" %>

app/views/campaigns/index.html.erb
<h1>All Campaigns</h1>

<h2>Recent Campaigns</h2>

<% @campaigns.each do |campaign| %>
  <%= cache campaign do %>
    <div class="well">
      <%= campaign.decorate.h3_title %> Total amount of pledges: <%= campaign.pledges.size %>
    <hr>
    </div>
  <% end %>
<% end %>

app/views/campaigns/new.html.erb
<h1>New Campaign</h1>
<%= render "form" %>

app/views/campaigns/show.html.erb
<div class="row">
  <div class="col-md-8">
    <h1><%= @campaign.title %></h1>
    <p><%= @campaign.body %></p>
    <p><%= @campaign.goal %></p>
    <p><%= @campaign.end_date %></p>

    <div>
      <div id="map" style='height: 400px;'></div>
    </div>
  </div>

<%= @campaign.publish_button %>

<%= link_to "Pledge", new_campaign_pledge_path(@campaign, class: "btn btn-primary") %>



  <div class="col-md-4">
    <% @campaign.rewards.each do |rew| %>
      <div class="panel panel-default">
        <div class="panel-heading"><%= number_to_currency(rew.amount) %></div>
        <div class="panel-body">
          <%= rew.description %>
        </div>
      </div>
    <% end  %>
  </div>
</div>




  <script>
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {
      mapTypeId: google.maps.MapTypeId.TERRAIN
    }, internal: {id: 'map'}}, function(){
      markers = handler.addMarkers([
        {
          "lat": <%= @campaign.latitude %>,
          "lng": <%= @campaign.longitude %>,
          "infowindow": "<%= @campaign.title %>"
        }
      ]);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
      handler.getMap().setZoom(15);
  });
  </script>