config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create]
  get "/auth/twitter", as: :sign_in_with_twitter
  get "/auth/twitter/callback" => "callbacks#twitter"

  resources :nearby_campaigns, only: [:index]

  resources :campaigns do
    resources :pledges, only: [:new, :create]
    resources :publishings, only: [] do
      patch :update, on: :collection
    end
  end

  resources :pledges, only: [] do
    resources :payments, only: [:new, :create]
  end

  root 'campaigns#index'

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :campaigns
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fundsy</title>
  <script src="//maps.google.com/maps/api/js?v=3.23&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script>
  <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
  <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
  <script type="text/javascript">
  Stripe.setPublishableKey('<%= Rails.application.secrets.stripe_publishable_key %>');
  </script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  </head>
<body>
<div class="container">
  <%= link_to "Home", root_path %>
  |
  <%= link_to "New Campaign", new_campaign_path %>
  |
  <% if user_signed_in? %>
  <%= link_to "Nearby Campaigns", nearby_campaigns_path %>
  |
    Hello, <%= current_user.full_name %>
    <% else %>
    <%= link_to "Sign Up", new_user_path %>
    <%= link_to "Sign In With Twitter", sign_in_with_twitter_path %>
  <% end %>

  <% if notice %>
     <div class="alert alert-success"><%= notice %></div>
   <% elsif alert %>
     <div class="alert alert-danger"><%= alert %></div>
   <% end %>

  <%= yield %>
  </div>
</body>
</html>